### ISSUE TITLE
Float amounts yield wrong derived values

### ISSUE THREAD

**Issue by nonvex** [jaidevd/numerizer#12]
Great library, thank you for your work.

The issue is that floats are not really matched against. In the example below, the regex will match only the last digit `2` from the `1.2`. Then it concatenates, resulting in a wrong value.

```py
from numerizer import numerize

In [0]: numerize("1.2 million")
Out[0]: '1.2000000'
```

**Comment by jaidevd** [comment]
Thanks, @nonvex for bringing this up.
And thanks, @nsj806 for the fix!

**Comment by jaidevd** [comment]
This fix just went into the latest release of numerizer. You can access it with 

```bash
pip install --upgrade numerizer
```

Thanks for the fix!
