### ISSUE TITLE
Only works with en_core_web_sm model

### ISSUE THREAD

**Issue by hakan-demirli** [jaidevd/numerizer#14]
There are three different spaCy models.
* en_core_web_sm
* en_core_web_md
* en_core_web_lg

Having one of them should be sufficient for the extension to work.
This part should be generalized:
https://github.com/jaidevd/numerizer/blob/328d58f62df2ed5e7f8bdbbe6b87295dc854084a/numerizer/numerizer.py#L5
**Current error:**
```py
>>> from numerizer import numerize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USR/.local/lib/python3.10/site-packages/numerizer/__init__.py", line 1, in <module>
    from .numerizer import numerize, spacy_numerize  # NOQA: F401
  File "/home/USR/.local/lib/python3.10/site-packages/numerizer/numerizer.py", line 5, in <module>
    nlp = spacy.load('en_core_web_sm')
  File "/home/USR/.local/lib/python3.10/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/home/USR/.local/lib/python3.10/site-packages/spacy/util.py", line 427, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
```
**Workaround:** Install the small model:
* `python3 -m spacy download en_core_web_sm`

**Comment by jaidevd** [comment]
Thanks a lot, @hakan-demirli for pointing this out, and apologies for the delay in responding.

Yes, this should work with any spaCy model, even a blank English one, to be honest.

I'll patch this up in a week.

**Comment by jaidevd** [comment]
Hi @hakan-demirli 

This is now fixed, and included in a new release. Please upgrade your installation of numerizer with 

```bash
pip install --upgrade numerizer
```

and it should work.

Thanks!
