### ISSUE TITLE
Problems with perenthesis and slash characters

### ISSUE THREAD

**Issue by jbonanat** [jaidevd/numerizer#16]
Hello,

I detected an issue with some inputs involving parenthesis and slash characters.
For example the text '2*(45+21)/6' is converted into '2*(45+211/6'
I fixed the error by replacing line 266 with:
`s = re.sub(r'(?:^|[a-zA-Z])\/(\d+)', r'1/\1', s)`

Thanks

**Comment by fchavat** [comment]
Any updates on this error?

**Comment by jaidevd** [comment]
Thanks for pointing this out, @jbonanat 

@fchavat it seems like you have OP both have a fix (and you've also written tests) for this. Could you please send a merge request?

I'll be happy to accept it and will publish the fixed version shortly thereafter.

**Comment by fchavat** [comment]
Great @jaidevd 
Thanks for the response.
I just created the PR for that.

**Comment by jaidevd** [comment]
Hi @jbonanat , @fchavat -

This fix has been included in the latest release. You can try it out with `pip install --upgrade numerizer`.

Thanks for the help
