### ISSUE TITLE
Error with 'a' being converted to 1

### ISSUE THREAD

**Issue by Caet-pip** [jaidevd/numerizer#24]
Hello, 
I am using numerizer directly from pip install. I guess one of the features is convertion every mention of 'a' in my text to 1 even if its not denoting 1.

Also for some one I get the same issue

Is there any workaround or fix for this?

**Comment by jaidevd** [comment]
Hello @Caet-pip,

I'm very sorry for the delay in responding. The easiest way to fix this is to use numerizer through spaCy, as follows:

```python
>>> from spacy import load
>>> from numerizer import numerize
>>> nlp = load('en_core_web_sm')
>>> nlp('A cat, a baby and a thousand puppies.')._.numerize()
{thousand: '1000'}

```

Thanks,
