### ISSUE TITLE
Experimental wrapper in R

### ISSUE THREAD

**Issue by amrrs** [jaidevd/numerizer#5]
Hey @jaidevd ,

Just tried to create an experimental wrapper of your package in R. It basically uses and still executes on your package. 

https://github.com/amrrs/numerizer 

Please give a try when you get time!

A

**Comment by jaidevd** [comment]
Thanks a lot, @amrrs !
I'll add this to the README.

**Comment by amrrs** [comment]
Thank you very much @jaidevd :) for adding it!
