### ISSUE TITLE
unable to numerize some numbers.

### ISSUE THREAD

**Issue by sagarpv23** [jaidevd/numerizer#6]
Unable to numerize 225755. i tried to numerize it using:
numerize('two hundred twenty fife thousand seven hundred and fifty-five')
but the output is:
225007 hundred 55
![numerize](https://user-images.githubusercontent.com/59719776/72126388-ef858180-3391-11ea-938b-e5ae8841287f.png)

**Comment by jaidevd** [comment]
Thanks for pointing this out, @sagarpv23 

This works properly in the [original ruby library](https://github.com/jduff/numerizer), so definitely a bug here.

**Comment by jaidevd** [comment]
@sagarpv23 This has been fixed in the latest release. Please install / upgrade numerizer with `pip install --upgrade numerizer` - and this should be fixed.

Thanks,
